### ISSUE TITLE
Not able to install.

### ISSUE THREAD

**Issue by shaksham95** [linuskohl/ambiverse-client#1]
Hey,

I a trying to install the ambiverse client using pip but it's giving the following error:

![image](https://user-images.githubusercontent.com/7498849/62455128-54a9cb00-b793-11e9-85ec-c660a15bf865.png)

Can you please help!!

**Comment by khadkechetan** [comment]
I am facing the same issue.

**Comment by linuskohl** [comment]
Thanks for your support!
